---
kind: Template
apiVersion: v1
metadata:
  name: my-python-app-template
  annotations:
    description: This is an unworking production frontend
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: my-python-app-prod
    labels:
      app: my-python-app
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: my-python-app-prod
    type: ClusterIP
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: my-python-app-prod
    labels:
      app: my-python-app
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 120
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - my-python-app
        from:
          kind: ImageStreamTag
          name: my-python-app:prod
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentconfig: my-python-app-prod
    template:
      metadata:
        labels:
          app: my-python-app
          deploymentconfig: my-python-app-prod
      spec:
        containers:
        - name: my-python-app
          image: " "
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
        restartPolicy: Always
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    labels:
      app: my-python-app
    name: my-python-app-prod
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: my-python-app-prod
parameters:
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
